site_name: Minha Documentação
nav:
  - Início: index.md
  - Guia do Usuário:
      - Instalação: guia/instrucoes.md
      - Configuração: guia/config.md
  - Api: api.md
  - Exemplos de diagrama: diagrama.md
  - Arquivos: files.md

#theme: readthedocs
theme:
  name: material
  features:
    - navigation.instant  # Carrega páginas sem recarregar o site
    - navigation.tabs  # Adiciona abas no menu
    - navigation.top  # Botão "voltar ao topo"
    - search.highlight  # Destaca palavras na pesquisa

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          #format: !!python/name:pymdownx.superfences.fence_code_format (Quando encontrar uma cerca de código com nome mermaid, use a função fence_code_format para processar o conteúdo antes de renderizar)
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.details

plugins:
  - search
  - awesome-pages
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true            
            docstring_style: google

#hooks:
#  - escreva um comando para ser executado(entrypoint). Ex: python main.py
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css
  - stylesheets/extra.css

