route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'default-receiver'

receivers:
- name: 'default-receiver'
  email_configs:
  - to: 'youremail@example.com'
    from: 'alertmanager@example.com'
    smarthost: 'smtp.example.com:587'
    auth_username: 'username'
    auth_password: 'password'
    require_tls: true

global:
  smtp_smarthost: 'smtp.yourdomain.com:587'
  smtp_from: 'alertmanager@yourdomain.com'
  smtp_auth_username: 'your-smtp-username'
  smtp_auth_password: 'your-smtp-password'
