version: '3'

services:
  store:
    image: linuxtips/nginx-prometheus-exporter:2.0.0
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        #Quando o cliente acessar a url do Host, o traefik ira redirecionar para o service da imagem acima
        - "traefik.http.routers.store.rule=Host(`store.biqueiranerd.com.br`)"
        - "traefik.http.routers.store.entrypoints=web"
        - "traefik.http.services.store.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true