name: Deploy MkDocs

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Instalar Poetry
        run : pipx install poetry

      - name: Instalar dependências
        run: poetry install --docs

      - name: Gerar e publicar documentação
        run: mkdocs gh-deploy --force
