name: Deploy MkDocs

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Instalar Poetry
        run: pipx install poetry

      - name: Instalar dependências
        run: poetry install --with docs --no-root

      - name: Gerar e publicar documentação
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: poetry run mkdocs gh-deploy --force
